version: "3.5"
services:
  vsftpd:
    image: siyuwuxin/vsftpd-alpine:latest
    expose:
      - "30022-30100"
    ports:
      - "20:20"
      - "21:21"
      - "30022-30100:30022-30100"
    volumes:
      - ./ftp/:/home/ftp/:rw
      - ./logs/vsftpd/:/var/log/vsftpd/:rw
    environment:
      - FTP_USER=myuser
      - FTP_PASS=mypass
      - PASV_ADDRESS=127.0.0.1
      - PASV_MIN_PORT=30022
      - PASV_MAX_PORT=30100
