version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./my-cert.pem:/etc/nginx/my-cert.pem
      - ./my-key.pem:/etc/nginx/my-key.pem
